export const presets = [
    {
        desc: 'Something1',
        cardBg: '#008d8d',
        image: '#', // items/...
        actionLeft: 'Left1',
        actionRight: 'Right1',
        effectLeft: [1, 2, 0], // only 0, 1(-1), 2(-2)
        effectRight: [-1, -2, -2], // only 0, 1(-1), 2(-2)
        code: '1', // tree on screenshot
        person: 'Somebody1',
    },
    {
        desc: 'Something2',
        cardBg: '#8d0071',
        image: '#',
        actionLeft: 'Left2',
        actionRight: 'Right2',
        effectLeft: [1, 2, 2],
        effectRight: [0, -2, -2],
        code: '11',
        person: 'Somebody2',
    },
    {
        desc: 'Something3',
        cardBg: '#c7af46',
        image: '#',
        actionLeft: 'Left3',
        actionRight: 'Right3',
        effectLeft: [1, 2, 2],
        effectRight: [-1, 0, -2],
        code: '12',
        person: 'Somebody3',
    },
    {
        desc: 'Something4',
        cardBg: '#7ac746',
        image: '#',
        actionLeft: 'Left4',
        actionRight: 'Right4',
        effectLeft: [1, 2, 2],
        effectRight: [-1, -2, -2],
        code: '111',
        person: 'Somebody4',
    },
    {
        desc: 'Something5',
        cardBg: '#c76d46',
        image: '#',
        actionLeft: 'Left5',
        actionRight: 'Right5',
        effectLeft: [1, 2, 2],
        effectRight: [-1, -2, -2],
        code: '112',
        person: 'Somebody5',
    },
    {
        desc: 'Something6',
        cardBg: '#be46c7',
        image: '#',
        actionLeft: 'Left6',
        actionRight: 'Right6',
        effectLeft: [1, 2, 2],
        effectRight: [-1, -2, -2],
        code: '121',
        person: 'Somebody6',
    },
    {
        desc: 'Something7',
        cardBg: '#46c76b',
        image: '#',
        actionLeft: 'Left7',
        actionRight: 'Right7',
        effectLeft: [1, 2, 2],
        effectRight: [-1, -2, -2],
        code: '122',
        person: 'Somebody7',
    },
]